name: Delete Database

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform repo
        uses: actions/checkout@v4
        with:
          repository: mugidavaatseren/db-terraform
          ref: main

      - name: List files in terraform_demo
        run: ls -ltra
        working-directory:  terraform_demo

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Validate
        run: terraform --version

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Terraform Init
        run: cd terraform_demo && terraform init

      - name: Terraform Plan
        env:
          TF_VAR_ssh_private_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          TF_VAR_deploy_dags: false
        run: cd terraform_demo && terraform plan --var "create_database=false"  --var "create_airflow=false"

      - name: Terraform Apply
        env:
          TF_VAR_ssh_private_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          TF_VAR_deploy_dags: false
        run: cd terraform_demo && terraform apply --var "create_database=false"  --var "create_airflow=false" -auto-approve
